apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: ghcr.io/nlnwa/veidemann-browser-controller
deploy:
  kustomize:
    paths:
      - github.com/nlnwa/veidemann/dev/veidemann/veidemann-harvester
