apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: norsknettarkiv/veidemann-browser-controller
deploy:
  kustomize:
    paths:
      - github.com/nlnwa/veidemann/bases/veidemann-harvester
