apiVersion: v1
browserScript:
  script: |-
    function loggedIn({returnTo}) {
        return {
            next: '',
            waitForData: false,
            data: {
                location: document.location.href
            }
        };
    }
  urlRegexp: []
id: 7cbfa19b-f128-45b0-9203-544611fe2066
kind: browserScript
meta:
  created: "2020-06-26T00:13:59.036Z"
  createdBy: admin@example.com
  description: ""
  label:
  - key: scope
    value: default
  lastModified: "2020-06-26T00:44:45.854Z"
  lastModifiedBy: admin@example.com
  name: loggedin.js

---
apiVersion: v1
browserScript:
  script: "function scrollTo({x, y}) {\n    window.scrollTo(x, y);\n    return {\n
    \       waitForData: true,\n        next: '',\n        data: null,    \n    };\n}"
  urlRegexp: []
id: cdf4f0b0-f5f0-4a80-8fb8-c275c4f36c7a
kind: browserScript
meta:
  created: "2020-06-25T19:37:21.656Z"
  createdBy: admin@example.com
  description: ""
  label:
  - key: scope
    value: default
  lastModified: "2020-06-25T23:36:22.536Z"
  lastModifiedBy: admin@example.com
  name: scrollTo.js

---
apiVersion: v1
browserScript:
  script: |-
    (function(window) {
    const framesDone = new Set();

    function compileOutlinks(frame) {
        framesDone.add(frame);
        if (frame && frame.document) {
            const outlinks = Array.from(frame.document.links);
            for (var i = 0; i < frame.frames.length; i++) {
                if (frame.frames[i] && !__brzl_framesDone.has(frame.frames[i])) {
                    try {
                        outlinks = outlinks.concat(compileOutlinks(frame.frames[i]));
                    } catch {}
                }
            }
            return outlinks;
        }
        return [];

    }

    return compileOutlinks(window).map(_ => _.href);
    )(window);
  urlRegexp: []
id: 85447607-5f9a-439c-a3f0-d83bccc117df
kind: browserScript
meta:
  created: "2020-06-25T17:21:08.793Z"
  createdBy: anonymous
  description: Script which extracts outlinks from <a href> tags
  label:
  - key: scope
    value: default
  lastModified: "2020-06-25T23:42:40.264Z"
  lastModifiedBy: admin@example.com
  name: extract-outlinks.js

---
apiVersion: v1
browserScript:
  script: |-
    function scroll({maxPages, page}) {
      const mp = parseInt(maxPages, 10)

      // height of visible area of window
      const windowHeight = window.innerHeight;

      // scroll down one page
      document.documentElement.scrollBy(0, windowHeight);

      // height of scrollable area
      const scrollHeight = document.documentElement.scrollHeight;

      // how far to scroll to top
      const scrollTop = Math.ceil(document.documentElement.scrollTop);
      const canScrollMore = scrollHeight > (scrollTop + windowHeight);

      // calculate current page from top (first page is 0)
      const page = Math.round(scrollTop windowHeight);
      return (canScrollMore && (page < mp))
        ? {
            waitForData: true,
            next: 'self',
            data: {maxPages}
          }
        : {
            waitForData: true,
            next: 'scrollTo.js',
            data: {x: 0, y: 0}
          };
    }
  urlRegexp: []
id: 8425c2fc-557b-4008-bd1c-043a3187292d
kind: browserScript
meta:
  created: "2020-06-25T18:16:16.293Z"
  createdBy: admin@example.com
  description: ""
  label:
  - key: scope
    value: default
  lastModified: "2020-06-25T23:42:28.429Z"
  lastModifiedBy: admin@example.com
  name: scroll.js

---
apiVersion: v1
browserScript:
  script: |-
    function goTo({url, next}) {
        const returnTo = window.document.location.href;
        window.document.location.assign(url);
        window.document.location.replace(url);

        return {
            next,
            waitForData: true,
            data: {returnTo}
        };
    }
  urlRegexp: []
id: 88034bfb-0805-45d7-9689-c9c378c24fb5
kind: browserScript
meta:
  created: "2020-06-25T23:40:42.448Z"
  createdBy: admin@example.com
  description: ""
  label:
  - key: scope
    value: default
  lastModified: "2020-06-26T00:42:56.388Z"
  lastModifiedBy: admin@example.com
  name: goToLogin.js

---
apiVersion: v1
browserScript:
  script: |-
    function login({returnTo, next, username, password}) {
      document.forms[0].elements[1].value = username;
      document.forms[0].elements[2].value = password;
      document.forms[0].elements[3].click()

      return {
                next,
                waitForData: true,
                data: {
                        returnTo,
                        location: document.location.href
                      }
             };
    }
  urlRegexp: []
id: b0dffd88-b593-4ec5-937a-346ad16a3b6c
kind: browserScript
meta:
  created: "2020-06-26T00:00:11.354Z"
  createdBy: admin@example.com
  description: ""
  label:
  - key: scope
    value: default
  lastModified: "2020-06-26T00:43:14.546Z"
  lastModifiedBy: admin@example.com
  name: login.js

---
