apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-harvester
spec:
  template:
    spec:
      containers:
        - name: veidemann-browser-controller
          env:
            - name: LOG_LEVEL
              value: DEBUG
        - name: veidemann-harvester-browser
          env:
            - name: DEBUG
              value: "browserless:*"
