apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: veidemann

commonLabels:
  app.kubernetes.io/instance: veidemann-harvester
  app.kubernetes.io/part-of: veidemann

resources:
  - github.com/nlnwa/veidemann/bases/veidemann-harvester

patchesStrategicMerge:
  - deployment_log_level_patch.yaml
